# Generated by Django 4.1.1 on 2022-09-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_carros_automatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('luxo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='carros',
            name='automatico',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carros',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca'),
        ),
    ]
