# Generated by Django 4.1.1 on 2022-09-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_marca_alter_carros_automatico_alter_carros_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='ano2',
            field=models.IntegerField(default=0),
        ),
    ]
