# Generated by Django 4.1.1 on 2022-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_carros_ano2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='marca',
            field=models.CharField(max_length=50),
        ),
    ]
